jenkins:
  systemMessage: "Controlled by Configuration as Code"

jobs:
  - script: >
      multibranchPipelineJob('self_k8s_portal_multibranch') {
          branchSources {
              branchSource {
                  source {
                      git {
                          remote('https://github.com/nilesh-nimawat/self_k8s_portal.git')
                          id('self-k8s-portal-id')
                      }
                  }
              }
          }
          # This tells Jenkins to look for the Jenkinsfile in the repo above
          factory {
              workflowBranchProjectFactory {
                  scriptPath('Jenkinsfile')
              }
          }
      }